sonar.projectKey=annacbrandao_gces-projetoindividual
sonar.organization=annacbrandao
sonar.projectName=gces-projetoindividual
sonar.sources=server
sonar.tests=server/tests
sonar.test.inclusions=server/tests/**/*.test.js
sonar.exclusions=server/tests/**
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
sonar.sourceEncoding=UTF-8
