apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mkjs
type: Opaque
stringData:
  POSTGRES_USER: mkjs
  POSTGRES_PASSWORD: mkjs_password
  POSTGRES_DB: mkjs_db
  DATABASE_URL: postgresql://mkjs:mkjs_password@postgres-service:5432/mkjs_db
