name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Instalar dependencias
        run: npm install
        working-directory: server

      - name: Lint do Backend
        run: npm run lint
        working-directory: server

      - name: Testes Unitarios
        run: npm test
        working-directory: server

      - name: SCA - Verificar vulnerabilidades nas dependencias
        run: npm audit --audit-level=high
        working-directory: server
